<?php get_header(); ?>

<main id="main" class="edu-page">
<style>
.edu-page{--b:#215af8;--n:#0b1220;--m:#667085;--l:#e5eaf1;--s:#f7f9fc;--g:#17a768;--p:#7047eb;background:#fff;color:var(--n);overflow:hidden}
.edu-page *{box-sizing:border-box}.edu-page .container{width:min(1180px,calc(100% - 40px));margin:auto}
.edux-edu-eye{font-size:12px;font-weight:850;letter-spacing:1.5px;color:var(--b);text-transform:uppercase;margin-bottom:14px}
.edux-edu-hero{padding:92px 0 100px;background:radial-gradient(circle at 82% 20%,#e8efff 0,transparent 32%),radial-gradient(circle at 96% 75%,#f1ebff 0,transparent 24%),linear-gradient(180deg,#fff,#f8faff)}
.edux-edu-hero-grid{display:grid;grid-template-columns:.93fr 1.07fr;gap:62px;align-items:center}
.edux-edu-hero h1{font-size:clamp(43px,5vw,67px);line-height:1.02;letter-spacing:-.045em;margin:0 0 22px;font-weight:850}.edux-edu-hero h1 em,.edux-edu-head h2 em,.edux-edu-copy h2 em{font-style:normal;color:var(--b)}
.edux-edu-hero-copy>p{font-size:18px;line-height:1.7;color:var(--m);margin:0 0 28px}.edux-edu-btns{display:flex;gap:12px;flex-wrap:wrap}.edux-edu-btn{display:inline-flex;align-items:center;gap:9px;padding:13px 20px;border-radius:10px;background:var(--b);color:#fff!important;text-decoration:none!important;font-weight:750;box-shadow:0 10px 25px rgba(33,90,248,.18)}.edux-edu-btn.edux-alt{background:#fff;color:var(--n)!important;border:1px solid var(--l);box-shadow:none}.edux-edu-proof{display:flex;gap:20px;flex-wrap:wrap;margin-top:25px;color:#475467;font-size:13px;font-weight:700}.edux-edu-proof span:before{content:"✓";color:var(--g);margin-right:6px}

/* hero CRM */
.edux-edu-app{background:#fff;border:1px solid #dfe6ef;border-radius:22px;box-shadow:0 28px 80px rgba(30,55,90,.14);overflow:hidden;position:relative}.edux-bar{height:44px;border-bottom:1px solid #e9edf3;display:flex;align-items:center;padding:0 14px;gap:6px;background:#fbfcfe}.edux-dot{width:8px;height:8px;border-radius:50%;background:#d9dee7}.edux-bar b{font-size:10px;color:#7a8494;margin-left:7px}.edux-body{display:grid;grid-template-columns:96px 1fr;min-height:445px}.edux-side{padding:16px 7px;border-right:1px solid #edf0f5;background:#f8faff}.edux-nav{padding:9px 6px;border-radius:7px;font-size:8px;font-weight:800;color:#667085;margin-bottom:5px}.edux-nav.edux-active{background:#e9f1ff;color:#215af8}.edux-dash{padding:18px}.edux-top{display:flex;justify-content:space-between;align-items:center}.edux-top strong{font-size:12px}.edux-live{font-size:7px;padding:5px 7px;border-radius:999px;background:#e9f8ef;color:#12824e;font-weight:900}.edux-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:13px 0}.edux-stat{border:1px solid #e7ebf1;border-radius:9px;padding:9px}.edux-stat small{font-size:6px;color:#98a2b3}.edux-stat b{font-size:14px;display:block;margin-top:3px}.edux-student{display:grid;grid-template-columns:29px 1fr auto;gap:8px;align-items:center;padding:9px;border:1px solid #e7ebf1;border-radius:9px;margin:6px 0}.edux-av{width:29px;height:29px;border-radius:50%;display:grid;place-items:center;background:#eaf1ff;color:#215af8;font-size:7px;font-weight:900}.edux-student b{font-size:8px;display:block}.edux-student small{font-size:6px;color:#98a2b3}.edux-tag{font-size:6px;font-weight:900;padding:4px 6px;border-radius:5px;background:#f4f6f9}.edux-auto{margin-top:10px;padding:10px;border-radius:10px;background:#f8f6ff;border:1px solid #e4dfff}.edux-auto b{font-size:8px;color:#6747d6}.edux-flow-mini{display:flex;gap:4px;align-items:center;flex-wrap:wrap;margin-top:7px}.edux-flow-mini span{font-size:6px;padding:5px 6px;background:#fff;border:1px solid #e5e0f7;border-radius:5px;font-weight:800}.edux-flow-mini i{font-style:normal;font-size:7px;color:#9aa4b2}.edux-floating{position:absolute;background:#fff;border:1px solid #e2e7ee;border-radius:9px;padding:8px 10px;font-size:8px;font-weight:850;box-shadow:0 12px 30px rgba(18,40,75,.13)}.edux-floating.edux-f1{right:12px;top:60px}.edux-floating.edux-f2{left:108px;bottom:14px}.edux-floating i{font-style:normal;color:var(--g)}

/* common */
.edux-edu-sec,.edux-edu-pipeline,.edux-edu-demo,.edux-edu-auto,.edux-edu-ai,.edux-edu-flow-sec{padding:94px 0}.edux-edu-pipeline,.edux-edu-auto,.edux-edu-ai{background:#f7f9fc}.edux-edu-head{text-align:center;max-width:800px;margin:0 auto 45px}.edux-edu-head h2,.edux-edu-copy h2{font-size:clamp(32px,4vw,49px);line-height:1.1;letter-spacing:-.035em;margin:0 0 14px}.edux-edu-head p,.edux-edu-copy p{color:var(--m);line-height:1.7;margin:0}
.edux-features{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.edux-card{padding:25px;border:1px solid var(--l);border-radius:17px;background:#fff;box-shadow:0 7px 26px rgba(16,32,56,.035)}.edux-ico{width:42px;height:42px;border-radius:11px;display:grid;place-items:center;background:#eaf1ff;color:var(--b);font-weight:900;margin-bottom:16px}.edux-card h3{font-size:16px;margin:0 0 8px}.edux-card p{font-size:13px;line-height:1.65;color:var(--m);margin:0}

/* pipeline */
.edux-pipeline{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.edux-stage{background:#fff;border:1px solid var(--l);border-radius:14px;padding:13px}.edux-stage-title{font-size:8px;font-weight:900;margin-bottom:10px}.edux-lead{padding:9px;border:1px solid #e7ebf1;border-radius:9px;margin:7px 0}.edux-lead b{font-size:8px;display:block}.edux-lead small{font-size:6px;color:#98a2b3}.edux-lead span{font-size:6px;font-weight:850;color:#215af8;display:block;margin-top:5px}

/* demo */
.edux-two{display:grid;grid-template-columns:1fr 1fr;gap:58px;align-items:center}.edux-demo-card{background:#fff;border:1px solid var(--l);border-radius:20px;padding:25px;box-shadow:0 22px 55px rgba(18,40,75,.08)}.edux-demo-card h3{font-size:15px;margin:0 0 5px}.edux-demo-card>p{font-size:10px;color:#98a2b3;margin:0 0 16px}.edux-field{border:1px solid #e4e8ef;border-radius:8px;padding:10px;margin-bottom:8px;font-size:9px;color:#7a8494}.edux-field b{color:#111827}.edux-field-row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.edux-submit{background:#215af8;color:#fff;border-radius:8px;text-align:center;padding:11px;font-size:9px;font-weight:900;margin-top:4px}.edux-demo-note{margin-top:10px;font-size:8px;color:#667085;text-align:center}.edux-checks{margin-top:22px}.edux-check{display:flex;gap:11px;margin:16px 0}.edux-check i{font-style:normal;width:25px;height:25px;border-radius:50%;display:grid;place-items:center;background:#e9f8ef;color:var(--g);font-size:11px;font-weight:900;flex:0 0 25px}.edux-check strong{font-size:14px}.edux-check p{font-size:13px!important;margin:3px 0 0!important;color:var(--m)}

/* automation */
.edux-auto-box{background:#fff;border:1px solid var(--l);border-radius:20px;padding:25px;box-shadow:0 22px 55px rgba(18,40,75,.08)}.edux-node{display:flex;align-items:center;gap:10px;padding:11px;border:1px solid #e6eaf0;border-radius:10px;max-width:380px;margin:auto}.edux-node span{width:30px;height:30px;border-radius:8px;background:#eaf1ff;color:#215af8;display:grid;place-items:center;font-size:9px;font-weight:900}.edux-node b{font-size:9px;display:block}.edux-node small{font-size:7px;color:#98a2b3}.edux-line{height:18px;width:2px;background:#dce2ea;margin:auto}

/* AI */
.edux-ai-box{background:#fff;border:1px solid var(--l);border-radius:20px;padding:25px;box-shadow:0 22px 55px rgba(18,40,75,.08)}.edux-ai-title{font-size:9px;color:#7047eb;font-weight:900}.edux-ai-result{padding:13px;border:1px solid #e4defa;background:#faf9ff;border-radius:10px;margin-top:10px}.edux-ai-result b{font-size:10px}.edux-ai-result p{font-size:9px;line-height:1.6;color:#606a79;margin:5px 0 0}.edux-suggest{display:flex;gap:9px;align-items:center;padding:10px;border:1px solid #e7ebf1;border-radius:9px;margin-top:8px}.edux-suggest i{font-style:normal;width:27px;height:27px;border-radius:7px;background:#f0edff;color:#6847d7;display:grid;place-items:center;font-size:9px;font-weight:900}.edux-suggest b{font-size:9px;display:block}.edux-suggest small{font-size:7px;color:#98a2b3}

/* flow */
.edux-flow{display:grid;grid-template-columns:repeat(7,1fr);gap:9px}.edux-step{position:relative;text-align:center;padding:18px 7px;border:1px solid var(--l);border-radius:13px;background:#fff}.edux-step:not(:last-child):after{content:"→";position:absolute;right:-12px;top:50%;transform:translateY(-50%);color:#9aa4b2;font-weight:900;z-index:2}.edux-num{width:29px;height:29px;border-radius:50%;display:grid;place-items:center;margin:0 auto 9px;background:#eaf1ff;color:#215af8;font-size:9px;font-weight:900}.edux-step strong{font-size:9px;display:block}.edux-step small{font-size:7px;line-height:1.4;color:#8a93a3;display:block;margin-top:4px}

/* CTA */
.edux-edu-cta{padding:42px 0 105px}.edux-cta{padding:56px;border-radius:27px;background:linear-gradient(135deg,#215af8,#173eb1);color:#fff;display:flex;align-items:center;justify-content:space-between;gap:35px;box-shadow:0 30px 70px rgba(33,90,248,.22)}.edux-cta h2{font-size:clamp(30px,4vw,46px);margin:0 0 8px;color:#fff}.edux-cta p{margin:0;color:#dce5ff}.edux-cta .edux-edu-btn{background:#fff;color:#15399e!important;white-space:nowrap}
@media(max-width:1000px){.edux-edu-hero-grid,.edux-two{grid-template-columns:1fr}.edux-features{grid-template-columns:1fr 1fr}.edux-pipeline{grid-template-columns:1fr 1fr}.edux-flow{grid-template-columns:repeat(2,1fr)}.edux-step:after{display:none}.edux-edu-app{max-width:720px;margin:auto}.edux-cta{flex-direction:column;align-items:flex-start}}
@media(max-width:640px){.edu-page .container{width:min(100% - 26px,1180px)}.edux-edu-hero{padding:70px 0}.edux-edu-hero h1{font-size:41px}.edux-features,.edux-pipeline,.edux-flow{grid-template-columns:1fr}.edux-floating{display:none}.edux-edu-sec,.edux-edu-pipeline,.edux-edu-demo,.edux-edu-auto,.edux-edu-ai,.edux-edu-flow-sec{padding:70px 0}.edux-cta{padding:34px 24px}}
</style>

<section class="edux-edu-hero"><div class="container edux-edu-hero-grid">
<div class="edux-edu-hero-copy"><div class="edux-edu-eye">AI-POWERED EDUCATION CRM</div><h1>Turn student enquiries into <em>enrolment opportunities.</em></h1><p>Capture student enquiries, organize course interests, assign counsellors and manage follow-ups. Track every prospect through your admissions pipeline and automate repetitive communication, all from one VistaarFlow workspace.</p><div class="edux-edu-btns"><a class="edux-edu-btn" href="https://app.vistaarflow.in/signup">Book a Demo →</a><a class="edux-edu-btn edux-alt" href="#education-features">Explore Education CRM</a></div><div class="edux-edu-proof"><span>Student lead tracking</span><span>Admissions automation</span><span>AI assistance</span></div></div>
<div class="edux-edu-app"><div class="edux-bar"><i class="edux-dot"></i><i class="edux-dot"></i><i class="edux-dot"></i><b>VistaarFlow • Education CRM</b></div><div class="edux-body"><aside class="edux-side"><div class="edux-nav edux-active">◉ Enquiries</div><div class="edux-nav">▥ Admissions</div><div class="edux-nav">✓ Tasks</div><div class="edux-nav">💬 WhatsApp</div><div class="edux-nav">⚡ Automation</div><div class="edux-nav">✦ AI</div></aside><div class="edux-dash"><div class="edux-top"><strong>Student Enquiries</strong><span class="edux-live">● ACTIVE</span></div><div class="edux-stats"><div class="edux-stat"><small>NEW ENQUIRIES</small><b>32</b></div><div class="edux-stat"><small>FOLLOW-UPS</small><b>14</b></div><div class="edux-stat"><small>ADMISSION OPPS</small><b>9</b></div></div><div class="edux-student"><span class="edux-av">AS</span><div><b>Aarav Shah</b><small>Full Stack Development</small></div><span class="edux-tag">NEW</span></div><div class="edux-student"><span class="edux-av">PK</span><div><b>Priya Kulkarni</b><small>Digital Marketing</small></div><span class="edux-tag">CONTACTED</span></div><div class="edux-student"><span class="edux-av">RM</span><div><b>Riya Mehta</b><small>Java / Spring Boot</small></div><span class="edux-tag">FOLLOW-UP</span></div><div class="edux-auto"><b>⚡ ADMISSIONS WORKFLOW</b><div class="edux-flow-mini"><span>Enquiry</span><i>→</i><span>Assign</span><i>→</i><span>Follow-up</span><i>→</i><span>Opportunity</span></div></div></div></div><span class="edux-floating edux-f1"><i>✓</i> New student enquiry</span><span class="edux-floating edux-f2"><i>✓</i> Counsellor assigned</span></div>
</div></section>

<section id="education-features" class="edux-edu-sec"><div class="container"><div class="edux-edu-head"><div class="edux-edu-eye">CRM FOR EDUCATION & TRAINING BUSINESSES</div><h2>Manage the complete <em>student enquiry journey.</em></h2><p>Build a CRM process around your admissions workflow, from the first enquiry to counselling, follow-up and enrolment.</p></div><div class="edux-features">
<article class="edux-card"><span class="edux-ico">◉</span><h3>Student Lead Management</h3><p>Store and organize student enquiries, contact details, course interests and other relevant information in one CRM.</p></article>
<article class="edux-card"><span class="edux-ico">▥</span><h3>Admissions Pipeline</h3><p>Create stages such as New Enquiry, Contacted, Counselling, Follow-up, Application and Enrolled to match your process.</p></article>
<article class="edux-card"><span class="edux-ico">⚡</span><h3>Admissions Automation</h3><p>Use workflows for lead assignment, follow-up tasks, reminders, notifications and supported communication actions.</p></article>
<article class="edux-card"><span class="edux-ico">✦</span><h3>AI Assistance</h3><p>Use AI summaries, reply drafts and next-action suggestions to help your team manage student conversations efficiently.</p></article>
</div></div></section>

<section class="edux-edu-pipeline"><div class="container"><div class="edux-edu-head"><div class="edux-edu-eye">ADMISSIONS PIPELINE</div><h2>See where every prospective <em>student stands.</em></h2><p>Use a custom pipeline that matches the way your institute, college, academy or training business handles admissions.</p></div><div class="edux-pipeline">
<div class="edux-stage"><div class="edux-stage-title">NEW ENQUIRY</div><div class="edux-lead"><b>Aarav Shah</b><small>Full Stack</small><span>Website Lead</span></div><div class="edux-lead"><b>Sana Khan</b><small>React</small><span>Meta Lead</span></div></div>
<div class="edux-stage"><div class="edux-stage-title">CONTACTED</div><div class="edux-lead"><b>Priya Kulkarni</b><small>Digital Marketing</small><span>Call completed</span></div></div>
<div class="edux-stage"><div class="edux-stage-title">COUNSELLING</div><div class="edux-lead"><b>Riya Mehta</b><small>Java / Spring Boot</small><span>Session planned</span></div></div>
<div class="edux-stage"><div class="edux-stage-title">FOLLOW-UP</div><div class="edux-lead"><b>Arjun Rao</b><small>Full Stack</small><span>Follow-up due</span></div></div>
<div class="edux-stage"><div class="edux-stage-title">ENROLMENT</div><div class="edux-lead"><b>Neha Joshi</b><small>React</small><span>Opportunity active</span></div></div>
</div></div></section>

<section class="edux-edu-demo"><div class="container edux-two"><div class="edux-edu-copy"><div class="edux-edu-eye">BOOK A DEMO</div><h2>See how VistaarFlow can fit <em>your admissions process.</em></h2><p>Book a VistaarFlow demo to see how your education business can manage enquiries, counsellor follow-ups, communication, automation and admissions pipelines in one CRM.</p><div class="edux-checks"><div class="edux-check"><i>✓</i><div><strong>Discuss your current enquiry process</strong><p>Walk through where your student leads come from today and how your team manages them.</p></div></div><div class="edux-check"><i>✓</i><div><strong>See a relevant CRM workflow</strong><p>Explore pipelines, custom fields, tasks, assignment and automation built around an education use case.</p></div></div><div class="edux-check"><i>✓</i><div><strong>Understand the next setup steps</strong><p>Learn how VistaarFlow can be configured around your business requirements.</p></div></div></div></div>
<div class="edux-demo-card"><h3>Book Your VistaarFlow Demo</h3><p>Tell us a little about your education business.</p><div class="edux-field">Name: <b>Your name</b></div><div class="edux-field-row"><div class="edux-field">Phone number</div><div class="edux-field">Work email</div></div><div class="edux-field">Institute / Business Name</div><div class="edux-field">Interested in: <b>Education CRM</b></div><div class="edux-field">Approx. enquiries per month</div><a href="https://app.vistaarflow.in/signup" class="edux-submit" style="display:block;color:#fff;text-decoration:none">BOOK A DEMO →</a><div class="edux-demo-note">Explore VistaarFlow for your admissions workflow.</div></div></div></section>

<section class="edux-edu-auto"><div class="container edux-two"><div class="edux-auto-box"><div class="edux-node"><span>01</span><div><small>TRIGGER</small><b>New student enquiry received</b></div></div><div class="edux-line"></div><div class="edux-node"><span>02</span><div><small>ASSIGNMENT</small><b>Assign counsellor / team member</b></div></div><div class="edux-line"></div><div class="edux-node"><span>03</span><div><small>FOLLOW-UP</small><b>Create task or configured communication action</b></div></div><div class="edux-line"></div><div class="edux-node"><span>04</span><div><small>PIPELINE</small><b>Continue admissions journey</b></div></div></div><div class="edux-edu-copy"><div class="edux-edu-eye">EDUCATION CRM AUTOMATION</div><h2>Automate repetitive admissions <em>follow-up work.</em></h2><p>Configure workflows around the way your admissions team works, so routine lead-management actions are not repeated manually for every enquiry.</p><div class="edux-checks"><div class="edux-check"><i>✓</i><div><strong>Automatic lead assignment</strong><p>Route new enquiries to the appropriate counsellor or configured team member.</p></div></div><div class="edux-check"><i>✓</i><div><strong>Tasks & reminders</strong><p>Create structured follow-up activity so every student enquiry stays visible to your team.</p></div></div><div class="edux-check"><i>✓</i><div><strong>WhatsApp templates</strong><p>Use approved WhatsApp templates as part of supported communication workflows.</p></div></div></div></div></div></section>

<section class="edux-edu-ai"><div class="container edux-two"><div class="edux-edu-copy"><div class="edux-edu-eye">AI FOR STUDENT CONVERSATIONS</div><h2>Understand enquiries and prepare <em>the next response faster.</em></h2><p>Use VistaarFlow AI assistance to summarize conversation context, prepare reply drafts and suggest useful next actions for your admissions team.</p><div class="edux-checks"><div class="edux-check"><i>✦</i><div><strong>AI Summary</strong><p>Quickly understand what the prospective student has discussed.</p></div></div><div class="edux-check"><i>✦</i><div><strong>AI Reply</strong><p>Generate a response draft that your team can review and edit before sending.</p></div></div><div class="edux-check"><i>✦</i><div><strong>AI Suggestions</strong><p>Surface useful next steps from the available conversation and CRM context.</p></div></div></div></div><div class="edux-ai-box"><div class="edux-ai-title">✦ VISTAARFLOW AI ASSISTANT</div><div class="edux-ai-result"><b>Student Enquiry Summary</b><p>Student is interested in the Full Stack Development course, asked about duration and fees, and is available for a counselling call tomorrow afternoon.</p></div><div class="edux-suggest"><i>01</i><div><b>Share course information</b><small>Student requested duration and fee details.</small></div></div><div class="edux-suggest"><i>02</i><div><b>Create counselling task</b><small>Student is available tomorrow afternoon.</small></div></div><div class="edux-suggest"><i>03</i><div><b>Prepare reply draft</b><small>Use conversation context to prepare the response.</small></div></div></div></div></section>

<section class="edux-edu-flow-sec"><div class="container"><div class="edux-edu-head"><div class="edux-edu-eye">CONNECTED ADMISSIONS WORKFLOW</div><h2>From student enquiry to <em>enrolment opportunity.</em></h2><p>Keep lead capture, assignment, communication, tasks, automation and pipeline tracking connected.</p></div><div class="edux-flow"><div class="edux-step"><span class="edux-num">01</span><strong>Enquiry</strong><small>Website, Meta, WhatsApp or another source</small></div><div class="edux-step"><span class="edux-num">02</span><strong>CRM Contact</strong><small>Student details are organized</small></div><div class="edux-step"><span class="edux-num">03</span><strong>Assign</strong><small>A counsellor takes ownership</small></div><div class="edux-step"><span class="edux-num">04</span><strong>Communicate</strong><small>WhatsApp, email or call</small></div><div class="edux-step"><span class="edux-num">05</span><strong>Follow-up</strong><small>Tasks and reminders</small></div><div class="edux-step"><span class="edux-num">06</span><strong>AI Assist</strong><small>Summary, reply, suggestions</small></div><div class="edux-step"><span class="edux-num">07</span><strong>Enrolment</strong><small>Track the opportunity</small></div></div></div></section>

<section class="edux-edu-cta"><div class="container"><div class="edux-cta"><div><h2>Build a smarter admissions workflow with VistaarFlow.</h2><p>Bring student enquiries, counsellor follow-ups, automation and AI assistance together in one CRM.</p></div><a class="edux-edu-btn" href="https://app.vistaarflow.in/signup">Book a Demo →</a></div></div></section>

</main>
<?php get_footer(); ?>