<?php get_header(); ?>

<main id="main" class="msme-page">
<style>
.msme-page{--b:#215af8;--n:#0b1220;--m:#667085;--l:#e5eaf1;--g:#17a768;--p:#7047eb;background:#fff;color:var(--n);overflow:hidden}
.msme-page *{box-sizing:border-box}.msme-page .container{width:min(1180px,calc(100% - 40px));margin:auto}
.msmex-ms-eye{font-size:12px;font-weight:850;letter-spacing:1.5px;color:var(--b);text-transform:uppercase;margin-bottom:14px}
.msmex-ms-hero{padding:92px 0 100px;background:radial-gradient(circle at 82% 20%,#e8efff 0,transparent 32%),radial-gradient(circle at 95% 75%,#effbf6 0,transparent 24%),linear-gradient(180deg,#fff,#f8faff)}
.msmex-ms-grid{display:grid;grid-template-columns:.93fr 1.07fr;gap:62px;align-items:center}
.msmex-ms-hero h1{font-size:clamp(43px,5vw,67px);line-height:1.02;letter-spacing:-.045em;margin:0 0 22px;font-weight:850}.msmex-ms-hero h1 em,.msmex-head h2 em,.msmex-copy h2 em{font-style:normal;color:var(--b)}
.msmex-ms-hero-copy>p{font-size:18px;line-height:1.7;color:var(--m);margin:0 0 28px}.msmex-btns{display:flex;gap:12px;flex-wrap:wrap}.msmex-ms-btn{display:inline-flex;align-items:center;gap:9px;padding:13px 20px;border-radius:10px;background:var(--b);color:#fff!important;text-decoration:none!important;font-weight:750;box-shadow:0 10px 25px rgba(33,90,248,.18)}.msmex-ms-btn.msmex-alt{background:#fff;color:var(--n)!important;border:1px solid var(--l);box-shadow:none}.msmex-proof{display:flex;gap:20px;flex-wrap:wrap;margin-top:25px;color:#475467;font-size:13px;font-weight:700}.msmex-proof span:before{content:"✓";color:var(--g);margin-right:6px}

/* App */
.msmex-app{background:#fff;border:1px solid #dfe6ef;border-radius:22px;box-shadow:0 28px 80px rgba(30,55,90,.14);overflow:hidden;position:relative}.msmex-bar{height:44px;border-bottom:1px solid #e9edf3;display:flex;align-items:center;padding:0 14px;gap:6px;background:#fbfcfe}.msmex-dot{width:8px;height:8px;border-radius:50%;background:#d9dee7}.msmex-bar b{font-size:10px;color:#7a8494;margin-left:7px}.msmex-body{display:grid;grid-template-columns:96px 1fr;min-height:445px}.msmex-side{padding:16px 7px;border-right:1px solid #edf0f5;background:#f8faff}.msmex-nav{padding:9px 6px;border-radius:7px;font-size:8px;font-weight:800;color:#667085;margin-bottom:5px}.msmex-nav.msmex-active{background:#e9f1ff;color:#215af8}.msmex-dash{padding:18px}.msmex-top{display:flex;justify-content:space-between;align-items:center}.msmex-top strong{font-size:12px}.msmex-live{font-size:7px;padding:5px 7px;border-radius:999px;background:#e9f8ef;color:#12824e;font-weight:900}.msmex-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:13px 0}.msmex-stat{border:1px solid #e7ebf1;border-radius:9px;padding:9px}.msmex-stat small{font-size:6px;color:#98a2b3}.msmex-stat b{font-size:14px;display:block;margin-top:3px}.msmex-lead{display:grid;grid-template-columns:29px 1fr auto;gap:8px;align-items:center;padding:9px;border:1px solid #e7ebf1;border-radius:9px;margin:6px 0}.msmex-av{width:29px;height:29px;border-radius:50%;display:grid;place-items:center;background:#eaf1ff;color:#215af8;font-size:7px;font-weight:900}.msmex-lead b{font-size:8px;display:block}.msmex-lead small{font-size:6px;color:#98a2b3}.msmex-tag{font-size:6px;font-weight:900;padding:4px 6px;border-radius:5px;background:#f4f6f9}.msmex-auto{margin-top:10px;padding:10px;border-radius:10px;background:#f8f6ff;border:1px solid #e4dfff}.msmex-auto b{font-size:8px;color:#6747d6}.msmex-mini{display:flex;gap:4px;align-items:center;flex-wrap:wrap;margin-top:7px}.msmex-mini span{font-size:6px;padding:5px 6px;background:#fff;border:1px solid #e5e0f7;border-radius:5px;font-weight:800}.msmex-mini i{font-style:normal;font-size:7px;color:#9aa4b2}.msmex-float{position:absolute;background:#fff;border:1px solid #e2e7ee;border-radius:9px;padding:8px 10px;font-size:8px;font-weight:850;box-shadow:0 12px 30px rgba(18,40,75,.13)}.msmex-f1{right:12px;top:60px}.msmex-f2{left:108px;bottom:14px}.msmex-float i{font-style:normal;color:var(--g)}

/* common */
.msmex-sec,.msmex-growth,.msmex-channels,.msmex-automation,.msmex-ai,.msmex-flow-sec{padding:94px 0}.msmex-growth,.msmex-channels,.msmex-ai{background:#f7f9fc}.msmex-head{text-align:center;max-width:800px;margin:0 auto 45px}.msmex-head h2,.msmex-copy h2{font-size:clamp(32px,4vw,49px);line-height:1.1;letter-spacing:-.035em;margin:0 0 14px}.msmex-head p,.msmex-copy p{color:var(--m);line-height:1.7;margin:0}
.msmex-features{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.msmex-card{padding:25px;border:1px solid var(--l);border-radius:17px;background:#fff;box-shadow:0 7px 26px rgba(16,32,56,.035)}.msmex-ico{width:42px;height:42px;border-radius:11px;display:grid;place-items:center;background:#eaf1ff;color:var(--b);font-weight:900;margin-bottom:16px}.msmex-card h3{font-size:16px;margin:0 0 8px}.msmex-card p{font-size:13px;line-height:1.65;color:var(--m);margin:0}

/* growth */
.msmex-growth-grid{display:grid;grid-template-columns:1fr 1fr;gap:58px;align-items:center}.msmex-growth-box{background:#fff;border:1px solid var(--l);border-radius:20px;padding:26px;box-shadow:0 22px 55px rgba(18,40,75,.08)}.msmex-growth-row{display:grid;grid-template-columns:42px 1fr auto;gap:11px;align-items:center;padding:12px;border-bottom:1px solid #edf0f4}.msmex-growth-row:last-child{border:0}.msmex-growth-icon{width:38px;height:38px;border-radius:10px;background:#eaf1ff;color:#215af8;display:grid;place-items:center;font-size:10px;font-weight:900}.msmex-growth-row b{font-size:10px;display:block}.msmex-growth-row small{font-size:8px;color:#98a2b3}.msmex-arrow{color:#17a768;font-size:14px;font-weight:900}.msmex-checks{margin-top:22px}.msmex-check{display:flex;gap:11px;margin:16px 0}.msmex-check i{font-style:normal;width:25px;height:25px;border-radius:50%;display:grid;place-items:center;background:#e9f8ef;color:var(--g);font-size:11px;font-weight:900;flex:0 0 25px}.msmex-check strong{font-size:14px}.msmex-check p{font-size:13px!important;margin:3px 0 0!important;color:var(--m)}

/* channels */
.msmex-channels-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:13px}.msmex-channel{background:#fff;border:1px solid var(--l);border-radius:15px;padding:20px}.msmex-channel span{width:37px;height:37px;border-radius:10px;background:#eaf1ff;color:#215af8;display:grid;place-items:center;font-size:10px;font-weight:900;margin-bottom:13px}.msmex-channel h3{font-size:14px;margin:0 0 7px}.msmex-channel p{font-size:12px;line-height:1.6;color:#667085;margin:0}

/* automation */
.msmex-auto-box{background:#fff;border:1px solid var(--l);border-radius:20px;padding:25px;box-shadow:0 22px 55px rgba(18,40,75,.08)}.msmex-node{display:flex;align-items:center;gap:10px;padding:11px;border:1px solid #e6eaf0;border-radius:10px;max-width:390px;margin:auto}.msmex-node span{width:30px;height:30px;border-radius:8px;background:#eaf1ff;color:#215af8;display:grid;place-items:center;font-size:9px;font-weight:900}.msmex-node b{font-size:9px;display:block}.msmex-node small{font-size:7px;color:#98a2b3}.msmex-line{height:18px;width:2px;background:#dce2ea;margin:auto}

/* AI */
.msmex-ai-box{background:#fff;border:1px solid var(--l);border-radius:20px;padding:25px;box-shadow:0 22px 55px rgba(18,40,75,.08)}.msmex-ai-title{font-size:9px;color:#7047eb;font-weight:900}.msmex-ai-result{padding:13px;border:1px solid #e4defa;background:#faf9ff;border-radius:10px;margin-top:10px}.msmex-ai-result b{font-size:10px}.msmex-ai-result p{font-size:9px;line-height:1.6;color:#606a79;margin:5px 0 0}.msmex-suggest{display:flex;gap:9px;align-items:center;padding:10px;border:1px solid #e7ebf1;border-radius:9px;margin-top:8px}.msmex-suggest i{font-style:normal;width:27px;height:27px;border-radius:7px;background:#f0edff;color:#6847d7;display:grid;place-items:center;font-size:9px;font-weight:900}.msmex-suggest b{font-size:9px;display:block}.msmex-suggest small{font-size:7px;color:#98a2b3}

/* flow */
.msmex-flow{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}.msmex-step{position:relative;text-align:center;padding:19px 8px;border:1px solid var(--l);border-radius:13px;background:#fff}.msmex-step:not(:last-child):after{content:"→";position:absolute;right:-13px;top:50%;transform:translateY(-50%);color:#9aa4b2;font-weight:900;z-index:2}.msmex-num{width:29px;height:29px;border-radius:50%;display:grid;place-items:center;margin:0 auto 9px;background:#eaf1ff;color:#215af8;font-size:9px;font-weight:900}.msmex-step strong{font-size:10px;display:block}.msmex-step small{font-size:7px;line-height:1.4;color:#8a93a3;display:block;margin-top:4px}

/* CTA */
.msmex-ms-cta{padding:42px 0 105px}.msmex-cta{padding:56px;border-radius:27px;background:linear-gradient(135deg,#215af8,#173eb1);color:#fff;display:flex;align-items:center;justify-content:space-between;gap:35px;box-shadow:0 30px 70px rgba(33,90,248,.22)}.msmex-cta h2{font-size:clamp(30px,4vw,46px);margin:0 0 8px;color:#fff}.msmex-cta p{margin:0;color:#dce5ff}.msmex-cta .msmex-ms-btn{background:#fff;color:#15399e!important;white-space:nowrap}
@media(max-width:1000px){.msmex-ms-grid,.msmex-growth-grid{grid-template-columns:1fr}.msmex-features,.msmex-channels-grid{grid-template-columns:1fr 1fr}.msmex-flow{grid-template-columns:repeat(2,1fr)}.msmex-step:after{display:none}.msmex-app{max-width:720px;margin:auto}.msmex-cta{flex-direction:column;align-items:flex-start}}
@media(max-width:640px){.msme-page .container{width:min(100% - 26px,1180px)}.msmex-ms-hero{padding:70px 0}.msmex-ms-hero h1{font-size:41px}.msmex-features,.msmex-channels-grid,.msmex-flow{grid-template-columns:1fr}.msmex-float{display:none}.msmex-sec,.msmex-growth,.msmex-channels,.msmex-automation,.msmex-ai,.msmex-flow-sec{padding:70px 0}.msmex-cta{padding:34px 24px}}
</style>

<section class="msmex-ms-hero"><div class="container msmex-ms-grid">
<div class="msmex-ms-hero-copy"><div class="msmex-ms-eye">CRM FOR SMALL BUSINESSES & MSMEs</div><h1>Build better customer processes as <em>your business grows.</em></h1><p>VistaarFlow gives growing small businesses and MSMEs one place to capture leads, manage customer conversations, track opportunities, automate repetitive work and use AI assistance, without turning everyday CRM work into a complicated process.</p><div class="msmex-btns"><a class="msmex-ms-btn" href="https://app.vistaarflow.in/signup">Start 14 days free →</a><a class="msmex-ms-btn msmex-alt" href="#msme-features">Explore CRM for MSMEs</a></div><div class="msmex-proof"><span>Affordable CRM</span><span>Automation</span><span>AI-powered workflows</span></div></div>
<div class="msmex-app"><div class="msmex-bar"><i class="msmex-dot"></i><i class="msmex-dot"></i><i class="msmex-dot"></i><b>VistaarFlow • Business Dashboard</b></div><div class="msmex-body"><aside class="msmex-side"><div class="msmex-nav msmex-active">◉ Leads</div><div class="msmex-nav">▥ Pipeline</div><div class="msmex-nav">💬 Chat</div><div class="msmex-nav">✓ Tasks</div><div class="msmex-nav">⚡ Automation</div><div class="msmex-nav">✦ AI</div></aside><div class="msmex-dash"><div class="msmex-top"><strong>Growing Business CRM</strong><span class="msmex-live">● ACTIVE</span></div><div class="msmex-stats"><div class="msmex-stat"><small>NEW LEADS</small><b>28</b></div><div class="msmex-stat"><small>FOLLOW-UPS</small><b>12</b></div><div class="msmex-stat"><small>OPPORTUNITIES</small><b>9</b></div></div><div class="msmex-lead"><span class="msmex-av">RS</span><div><b>Rahul Sharma</b><small>Website enquiry</small></div><span class="msmex-tag">NEW</span></div><div class="msmex-lead"><span class="msmex-av">AP</span><div><b>Ananya Patel</b><small>WhatsApp enquiry</small></div><span class="msmex-tag">FOLLOW-UP</span></div><div class="msmex-lead"><span class="msmex-av">VM</span><div><b>Vikram Mehta</b><small>Meta lead</small></div><span class="msmex-tag">QUALIFIED</span></div><div class="msmex-auto"><b>⚡ AUTOMATION ACTIVE</b><div class="msmex-mini"><span>Lead</span><i>→</i><span>Assign</span><i>→</i><span>Follow-up</span><i>→</i><span>Opportunity</span></div></div></div></div><span class="msmex-float msmex-f1"><i>✓</i> New lead captured</span><span class="msmex-float msmex-f2"><i>✓</i> Follow-up task created</span></div>
</div></section>

<section id="msme-features" class="msmex-sec"><div class="container"><div class="msmex-head"><div class="msmex-ms-eye">ONE CRM FOR A GROWING BUSINESS</div><h2>Start simple. <em>Build better processes as you grow.</em></h2><p>Keep leads, customer information, conversations, pipelines and daily follow-up work connected in one workspace.</p></div><div class="msmex-features">
<article class="msmex-card"><span class="msmex-ico">◉</span><h3>Lead Management</h3><p>Capture, organize and track customer enquiries so your team has one place to manage potential business.</p></article>
<article class="msmex-card"><span class="msmex-ico">▥</span><h3>Flexible Pipelines</h3><p>Create pipelines and stages around your actual business process, from first enquiry to completed opportunity.</p></article>
<article class="msmex-card"><span class="msmex-ico">⚡</span><h3>Automation</h3><p>Reduce repetitive work with configured follow-ups, reminders, lead assignment, stage updates and team notifications.</p></article>
<article class="msmex-card"><span class="msmex-ico">✦</span><h3>AI Assistance</h3><p>Use AI summaries, reply drafts and contextual suggestions to understand conversations and prepare next actions.</p></article>
</div></div></section>

<section class="msmex-growth"><div class="container msmex-growth-grid"><div class="msmex-growth-box"><div class="msmex-growth-row"><span class="msmex-growth-icon">01</span><div><b>Capture enquiries</b><small>Bring customer leads into one CRM</small></div><span class="msmex-arrow">→</span></div><div class="msmex-growth-row"><span class="msmex-growth-icon">02</span><div><b>Organize follow-ups</b><small>Tasks, reminders and ownership</small></div><span class="msmex-arrow">→</span></div><div class="msmex-growth-row"><span class="msmex-growth-icon">03</span><div><b>Automate routine work</b><small>Use repeatable CRM workflows</small></div><span class="msmex-arrow">→</span></div><div class="msmex-growth-row"><span class="msmex-growth-icon">04</span><div><b>Track opportunities</b><small>See progress through your pipeline</small></div><span class="msmex-arrow">→</span></div><div class="msmex-growth-row"><span class="msmex-growth-icon">05</span><div><b>Grow with clearer processes</b><small>Keep your team working from shared context</small></div><span class="msmex-arrow">↗</span></div></div><div class="msmex-copy"><div class="msmex-ms-eye">BUILT FOR BUSINESS GROWTH</div><h2>Move beyond spreadsheets and <em>scattered follow-ups.</em></h2><p>As a small business grows, leads arrive from more channels and more people get involved in sales and customer service. VistaarFlow keeps that activity structured in one CRM.</p><div class="msmex-checks"><div class="msmex-check"><i>✓</i><div><strong>Clear customer ownership</strong><p>Assign leads and keep the responsible team member visible.</p></div></div><div class="msmex-check"><i>✓</i><div><strong>Repeatable processes</strong><p>Build pipelines and workflows around the way your business operates.</p></div></div><div class="msmex-check"><i>✓</i><div><strong>Shared customer context</strong><p>Keep contacts, opportunities, tasks and communication together in one place.</p></div></div></div></div></div></section>

<section class="msmex-channels"><div class="container"><div class="msmex-head"><div class="msmex-ms-eye">BRING YOUR LEADS TOGETHER</div><h2>Manage enquiries from <em>multiple business channels.</em></h2><p>Keep supported lead and communication sources connected to one customer-management process.</p></div><div class="msmex-channels-grid">
<article class="msmex-channel"><span>WEB</span><h3>Website Leads</h3><p>Capture submitted website-form information and organize it in your CRM workflow.</p></article>
<article class="msmex-channel"><span>WA</span><h3>WhatsApp</h3><p>Manage supported customer conversations, approved templates and WhatsApp Flows with CRM context.</p></article>
<article class="msmex-channel"><span>f</span><h3>Meta Leads</h3><p>Bring supported Facebook and Instagram Lead Ads enquiries into your lead-management process.</p></article>
<article class="msmex-channel"><span>✉</span><h3>Email</h3><p>Keep supported customer email communication alongside contacts and opportunities.</p></article>
<article class="msmex-channel"><span>☎</span><h3>Telephony</h3><p>Connect supported third-party telephony services and keep call activity with the customer record.</p></article>
<article class="msmex-channel"><span>Z</span><h3>Connected Apps</h3><p>Use supported integrations such as Zapier to connect compatible external business tools.</p></article>
<article class="msmex-channel"><span>▤</span><h3>CSV Imports</h3><p>Bring existing customer or lead lists into your CRM and continue working from structured records.</p></article>
<article class="msmex-channel"><span>+</span><h3>Custom Business Process</h3><p>Use custom fields and flexible pipelines to adapt VistaarFlow to your business.</p></article>
</div></div></section>

<section class="msmex-automation"><div class="container msmex-growth-grid"><div class="msmex-copy"><div class="msmex-ms-eye">AUTOMATION FOR EVERYDAY WORK</div><h2>Spend less time repeating <em>the same CRM actions.</em></h2><p>Configure workflows to handle routine actions around new leads and follow-ups, so your team can focus on customer conversations and opportunities.</p><div class="msmex-checks"><div class="msmex-check"><i>✓</i><div><strong>Automatic lead assignment</strong><p>Route incoming leads to configured users or teams.</p></div></div><div class="msmex-check"><i>✓</i><div><strong>Tasks and reminders</strong><p>Create structured follow-up activity around your customer journey.</p></div></div><div class="msmex-check"><i>✓</i><div><strong>Workflow actions</strong><p>Use supported stage updates, notifications and communication actions in configured workflows.</p></div></div></div></div><div class="msmex-auto-box"><div class="msmex-node"><span>01</span><div><small>TRIGGER</small><b>New customer lead received</b></div></div><div class="msmex-line"></div><div class="msmex-node"><span>02</span><div><small>ASSIGN</small><b>Route to the relevant team member</b></div></div><div class="msmex-line"></div><div class="msmex-node"><span>03</span><div><small>FOLLOW-UP</small><b>Create configured task / reminder</b></div></div><div class="msmex-line"></div><div class="msmex-node"><span>04</span><div><small>PIPELINE</small><b>Continue opportunity workflow</b></div></div></div></div></section>

<section class="msmex-ai"><div class="container msmex-growth-grid"><div class="msmex-ai-box"><div class="msmex-ai-title">✦ VISTAARFLOW AI ASSISTANT</div><div class="msmex-ai-result"><b>Customer Conversation Summary</b><p>Customer is interested in the service, requested pricing information and would like a follow-up call tomorrow morning.</p></div><div class="msmex-suggest"><i>01</i><div><b>Share pricing details</b><small>Customer requested more information.</small></div></div><div class="msmex-suggest"><i>02</i><div><b>Create follow-up task</b><small>Customer prefers tomorrow morning.</small></div></div><div class="msmex-suggest"><i>03</i><div><b>Prepare AI reply</b><small>Generate a contextual draft for review.</small></div></div></div><div class="msmex-copy"><div class="msmex-ms-eye">AI-POWERED CRM</div><h2>Give a growing team <em>more useful customer context.</em></h2><p>Use AI assistance to summarize conversations, prepare reply drafts and surface practical next-action suggestions inside your CRM workflow.</p><div class="msmex-checks"><div class="msmex-check"><i>✦</i><div><strong>AI Summary</strong><p>Turn lengthy conversations into a concise overview.</p></div></div><div class="msmex-check"><i>✦</i><div><strong>AI Reply</strong><p>Prepare a contextual reply draft for your team to review before sending.</p></div></div><div class="msmex-check"><i>✦</i><div><strong>AI Suggestions</strong><p>Surface useful next actions from available customer and CRM context.</p></div></div></div></div></div></section>

<section class="msmex-flow-sec"><div class="container"><div class="msmex-head"><div class="msmex-ms-eye">A SIMPLE GROWTH WORKFLOW</div><h2>From new enquiry to <em>business opportunity.</em></h2><p>Keep your lead journey structured as your customer base and team grow.</p></div><div class="msmex-flow"><div class="msmex-step"><span class="msmex-num">01</span><strong>Capture Lead</strong><small>Bring the enquiry into your CRM</small></div><div class="msmex-step"><span class="msmex-num">02</span><strong>Assign Owner</strong><small>Give clear responsibility</small></div><div class="msmex-step"><span class="msmex-num">03</span><strong>Communicate</strong><small>Continue the customer conversation</small></div><div class="msmex-step"><span class="msmex-num">04</span><strong>Automate</strong><small>Tasks, reminders and workflows</small></div><div class="msmex-step"><span class="msmex-num">05</span><strong>Track</strong><small>Manage the opportunity</small></div><div class="msmex-step"><span class="msmex-num">06</span><strong>Grow</strong><small>Build repeatable processes</small></div></div></div></section>

<section class="msmex-ms-cta"><div class="container"><div class="msmex-cta"><div><h2>A practical CRM for growing small businesses and MSMEs.</h2><p>Bring leads, communication, automation, pipelines and AI assistance together with VistaarFlow.</p></div><a class="msmex-ms-btn" href="https://app.vistaarflow.in/signup">Start 14 days free →</a></div></div></section>
</main>

<?php get_footer(); ?>