<?php get_header(); ?>

<main id="main" class="re-page">
<style>
.re-page{--b:#215af8;--n:#0b1220;--m:#667085;--l:#e5eaf1;--s:#f7f9fc;--g:#17a768;--p:#7047eb;background:#fff;color:var(--n);overflow:hidden}
.re-page *{box-sizing:border-box}.re-page .container{width:min(1180px,calc(100% - 40px));margin:auto}
.rex-re-eye{font-size:12px;font-weight:850;letter-spacing:1.5px;color:var(--b);text-transform:uppercase;margin-bottom:14px}
.rex-re-hero{padding:92px 0 100px;background:radial-gradient(circle at 82% 20%,#e8efff 0,transparent 32%),radial-gradient(circle at 95% 70%,#f1ebff 0,transparent 25%),linear-gradient(180deg,#fff,#f8faff)}
.rex-re-hero-grid{display:grid;grid-template-columns:.93fr 1.07fr;gap:62px;align-items:center}
.rex-re-hero h1{font-size:clamp(43px,5vw,67px);line-height:1.02;letter-spacing:-.045em;margin:0 0 22px;font-weight:850}.rex-re-hero h1 em,.rex-re-head h2 em,.rex-re-copy h2 em{font-style:normal;color:var(--b)}
.rex-re-hero-copy>p{font-size:18px;line-height:1.7;color:var(--m);margin:0 0 28px}.rex-re-btns{display:flex;gap:12px;flex-wrap:wrap}.rex-re-btn{display:inline-flex;align-items:center;gap:9px;padding:13px 20px;border-radius:10px;background:var(--b);color:#fff!important;text-decoration:none!important;font-weight:750;box-shadow:0 10px 25px rgba(33,90,248,.18)}.rex-re-btn.rex-alt{background:#fff;color:var(--n)!important;border:1px solid var(--l);box-shadow:none}.rex-re-proof{display:flex;gap:20px;flex-wrap:wrap;margin-top:25px;color:#475467;font-size:13px;font-weight:700}.rex-re-proof span:before{content:"✓";color:var(--g);margin-right:6px}

/* CRM hero */
.rex-crm{background:#fff;border:1px solid #dfe6ef;border-radius:22px;box-shadow:0 28px 80px rgba(30,55,90,.14);overflow:hidden;position:relative}.rex-bar{height:44px;border-bottom:1px solid #e9edf3;display:flex;align-items:center;padding:0 14px;gap:6px;background:#fbfcfe}.rex-dot{width:8px;height:8px;border-radius:50%;background:#d9dee7}.rex-bar b{font-size:10px;color:#7a8494;margin-left:7px}.rex-body{display:grid;grid-template-columns:95px 1fr;min-height:445px}.rex-side{padding:16px 7px;border-right:1px solid #edf0f5;background:#f8faff}.rex-nav{padding:9px 6px;border-radius:7px;font-size:8px;font-weight:800;color:#667085;margin-bottom:5px}.rex-nav.rex-active{background:#e9f1ff;color:#215af8}.rex-dash{padding:18px}.rex-dash-top{display:flex;justify-content:space-between;align-items:center}.rex-dash-top strong{font-size:12px}.rex-live{font-size:7px;padding:5px 7px;border-radius:999px;background:#e9f8ef;color:#12824e;font-weight:900}.rex-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:13px 0}.rex-stat{border:1px solid #e7ebf1;border-radius:9px;padding:9px}.rex-stat small{font-size:6px;color:#98a2b3}.rex-stat b{font-size:14px;display:block;margin-top:3px}.rex-lead{display:grid;grid-template-columns:29px 1fr auto;gap:8px;align-items:center;padding:9px;border:1px solid #e7ebf1;border-radius:9px;margin:6px 0}.rex-av{width:29px;height:29px;border-radius:50%;display:grid;place-items:center;background:#eaf1ff;color:#215af8;font-size:7px;font-weight:900}.rex-lead b{font-size:8px;display:block}.rex-lead small{font-size:6px;color:#98a2b3}.rex-src{font-size:6px;font-weight:900;padding:4px 6px;border-radius:5px;background:#f4f6f9}.rex-auto{margin-top:10px;padding:10px;border-radius:10px;background:#f8f6ff;border:1px solid #e4dfff}.rex-auto b{font-size:8px;color:#6747d6}.rex-auto-flow{display:flex;gap:4px;align-items:center;flex-wrap:wrap;margin-top:7px}.rex-auto-flow span{font-size:6px;padding:5px 6px;background:#fff;border:1px solid #e5e0f7;border-radius:5px;font-weight:800}.rex-auto-flow i{font-style:normal;font-size:7px;color:#9aa4b2}.rex-float{position:absolute;background:#fff;border:1px solid #e2e7ee;border-radius:9px;padding:8px 10px;font-size:8px;font-weight:850;box-shadow:0 12px 30px rgba(18,40,75,.13)}.rex-float.rex-f1{right:12px;top:60px}.rex-float.rex-f2{left:108px;bottom:14px}.rex-float i{font-style:normal;color:var(--g)}

/* common */
.rex-re-sec,.rex-re-sources,.rex-re-wa,.rex-re-track,.rex-re-ai,.rex-re-flow-sec{padding:94px 0}.rex-re-sources,.rex-re-track,.rex-re-ai{background:#f7f9fc}.rex-re-head{text-align:center;max-width:800px;margin:0 auto 45px}.rex-re-head h2,.rex-re-copy h2{font-size:clamp(32px,4vw,49px);line-height:1.1;letter-spacing:-.035em;margin:0 0 14px}.rex-re-head p,.rex-re-copy p{color:var(--m);line-height:1.7;margin:0}
.rex-features{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.rex-card{padding:25px;border:1px solid var(--l);border-radius:17px;background:#fff;box-shadow:0 7px 26px rgba(16,32,56,.035)}.rex-ico{width:42px;height:42px;border-radius:11px;display:grid;place-items:center;background:#eaf1ff;color:var(--b);font-weight:900;margin-bottom:16px}.rex-card h3{font-size:16px;margin:0 0 8px}.rex-card p{font-size:13px;line-height:1.65;color:var(--m);margin:0}

/* sources */
.rex-sources{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.rex-source{background:#fff;border:1px solid var(--l);border-radius:15px;padding:20px}.rex-source-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:13px}.rex-source-icon{width:37px;height:37px;border-radius:10px;background:#eaf1ff;color:#215af8;display:grid;place-items:center;font-size:11px;font-weight:900}.rex-source-tag{font-size:7px;font-weight:900;color:#12824e;background:#e9f8ef;padding:5px 7px;border-radius:999px}.rex-source h3{font-size:14px;margin:0 0 7px}.rex-source p{font-size:12px;line-height:1.6;color:#667085;margin:0}

/* WhatsApp */
.rex-two{display:grid;grid-template-columns:1fr 1fr;gap:58px;align-items:center}.rex-phone{max-width:390px;margin:auto;background:#fff;border:1px solid var(--l);border-radius:24px;padding:13px;box-shadow:0 22px 55px rgba(18,40,75,.1)}.rex-phone-in{background:#f4f7f5;border-radius:17px;overflow:hidden}.rex-phone-head{padding:13px;background:#fff;border-bottom:1px solid #e6ebe8;font-size:10px;font-weight:850}.rex-chat{padding:15px;min-height:310px}.rex-bubble{max-width:84%;padding:9px 10px;border-radius:10px;font-size:8px;line-height:1.5;margin:8px 0}.rex-in{background:#fff}.rex-out{background:#dff7d9;margin-left:auto}.rex-template{margin-top:14px;background:#fff;border:1px solid #e0e6e2;border-radius:10px;padding:11px}.rex-template small{font-size:6px;color:#17a768;font-weight:900}.rex-template b{display:block;font-size:8px;margin:5px 0}.rex-template p{font-size:7px;line-height:1.5;color:#667085;margin:0}.rex-checks{margin-top:22px}.rex-check{display:flex;gap:11px;margin:16px 0}.rex-check i{font-style:normal;width:25px;height:25px;border-radius:50%;display:grid;place-items:center;background:#e9f8ef;color:var(--g);font-size:11px;font-weight:900;flex:0 0 25px}.rex-check strong{font-size:14px}.rex-check p{font-size:13px!important;margin:3px 0 0!important;color:var(--m)}

/* tracking */
.rex-pipeline{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.rex-stage{background:#fff;border:1px solid var(--l);border-radius:14px;padding:14px}.rex-stage-title{font-size:9px;font-weight:900;margin-bottom:11px}.rex-deal{padding:10px;border:1px solid #e7ebf1;border-radius:9px;margin:7px 0}.rex-deal b{font-size:8px;display:block}.rex-deal small{font-size:6px;color:#98a2b3}.rex-deal span{font-size:6px;font-weight:850;color:#215af8;display:block;margin-top:5px}

/* AI */
.rex-ai-box{background:#fff;border:1px solid var(--l);border-radius:20px;padding:25px;box-shadow:0 22px 55px rgba(18,40,75,.08)}.rex-ai-label{font-size:9px;font-weight:900;color:#7047eb}.rex-ai-result{padding:13px;border:1px solid #e4defa;background:#faf9ff;border-radius:10px;margin-top:10px}.rex-ai-result b{font-size:10px}.rex-ai-result p{font-size:9px;line-height:1.6;color:#606a79;margin:5px 0 0}.rex-suggest{display:flex;gap:9px;align-items:center;padding:10px;border:1px solid #e7ebf1;border-radius:9px;margin-top:8px}.rex-suggest i{font-style:normal;width:27px;height:27px;border-radius:7px;background:#f0edff;color:#6847d7;display:grid;place-items:center;font-size:9px;font-weight:900}.rex-suggest b{font-size:9px;display:block}.rex-suggest small{font-size:7px;color:#98a2b3}

/* workflow */
.rex-flow{display:grid;grid-template-columns:repeat(7,1fr);gap:9px}.rex-step{position:relative;text-align:center;padding:18px 7px;border:1px solid var(--l);border-radius:13px;background:#fff}.rex-step:not(:last-child):after{content:"→";position:absolute;right:-12px;top:50%;transform:translateY(-50%);color:#9aa4b2;font-weight:900;z-index:2}.rex-num{width:29px;height:29px;border-radius:50%;display:grid;place-items:center;margin:0 auto 9px;background:#eaf1ff;color:#215af8;font-size:9px;font-weight:900}.rex-step strong{font-size:9px;display:block}.rex-step small{font-size:7px;line-height:1.4;color:#8a93a3;display:block;margin-top:4px}

/* CTA */
.rex-re-cta{padding:42px 0 105px}.rex-cta{padding:56px;border-radius:27px;background:linear-gradient(135deg,#215af8,#173eb1);color:#fff;display:flex;align-items:center;justify-content:space-between;gap:35px;box-shadow:0 30px 70px rgba(33,90,248,.22)}.rex-cta h2{font-size:clamp(30px,4vw,46px);margin:0 0 8px;color:#fff}.rex-cta p{margin:0;color:#dce5ff}.rex-cta .rex-re-btn{background:#fff;color:#15399e!important;white-space:nowrap}
@media(max-width:1000px){.rex-re-hero-grid,.rex-two{grid-template-columns:1fr}.rex-features,.rex-sources{grid-template-columns:1fr 1fr}.rex-flow{grid-template-columns:repeat(2,1fr)}.rex-step:after{display:none}.rex-pipeline{grid-template-columns:1fr 1fr}.rex-crm{max-width:720px;margin:auto}.rex-cta{flex-direction:column;align-items:flex-start}}
@media(max-width:640px){.re-page .container{width:min(100% - 26px,1180px)}.rex-re-hero{padding:70px 0}.rex-re-hero h1{font-size:41px}.rex-features,.rex-sources,.rex-pipeline,.rex-flow{grid-template-columns:1fr}.rex-float{display:none}.rex-re-sec,.rex-re-sources,.rex-re-wa,.rex-re-track,.rex-re-ai,.rex-re-flow-sec{padding:70px 0}.rex-cta{padding:34px 24px}}
</style>

<section class="rex-re-hero"><div class="container rex-re-hero-grid">
 <div class="rex-re-hero-copy"><div class="rex-re-eye">AI-POWERED REAL ESTATE CRM</div><h1>Capture every property lead. <em>Follow up from one CRM.</em></h1><p>Bring real estate enquiries from Facebook and Instagram Lead Ads, WhatsApp, property portals, your website, email and connected apps into VistaarFlow. Track every lead through your pipeline, automate follow-ups and use AI assistance to understand conversations and prepare the next action.</p><div class="rex-re-btns"><a class="rex-re-btn" href="https://app.vistaarflow.in/signup">Start 14 days free →</a><a class="rex-re-btn rex-alt" href="#real-estate-features">Explore Real Estate CRM</a></div><div class="rex-re-proof"><span>Multi-source leads</span><span>WhatsApp automation</span><span>AI assistance</span></div></div>
 <div class="rex-crm"><div class="rex-bar"><i class="rex-dot"></i><i class="rex-dot"></i><i class="rex-dot"></i><b>VistaarFlow • Real Estate CRM</b></div><div class="rex-body"><aside class="rex-side"><div class="rex-nav rex-active">◉ Leads</div><div class="rex-nav">▥ Pipeline</div><div class="rex-nav">💬 WhatsApp</div><div class="rex-nav">⚡ Automation</div><div class="rex-nav">✦ AI</div><div class="rex-nav">✓ Tasks</div></aside><div class="rex-dash"><div class="rex-dash-top"><strong>New Property Leads</strong><span class="rex-live">● LIVE</span></div><div class="rex-stats"><div class="rex-stat"><small>NEW LEADS</small><b>24</b></div><div class="rex-stat"><small>FOLLOW-UPS</small><b>11</b></div><div class="rex-stat"><small>OPPORTUNITIES</small><b>8</b></div></div><div class="rex-lead"><span class="rex-av">RS</span><div><b>Rahul Sharma</b><small>2 BHK enquiry</small></div><span class="rex-src">META</span></div><div class="rex-lead"><span class="rex-av">AP</span><div><b>Ananya Patel</b><small>Site visit enquiry</small></div><span class="rex-src">WHATSAPP</span></div><div class="rex-lead"><span class="rex-av">VM</span><div><b>Vikram Mehta</b><small>Property enquiry</small></div><span class="rex-src">PORTAL</span></div><div class="rex-auto"><b>⚡ AUTOMATION ACTIVE</b><div class="rex-auto-flow"><span>Lead Captured</span><i>→</i><span>Assign Agent</span><i>→</i><span>WhatsApp</span><i>→</i><span>Follow-up</span></div></div></div></div><span class="rex-float rex-f1"><i>✓</i> New Meta lead captured</span><span class="rex-float rex-f2"><i>✓</i> WhatsApp template ready</span></div>
</div></section>

<section id="real-estate-features" class="rex-re-sec"><div class="container"><div class="rex-re-head"><div class="rex-re-eye">ONE CRM FOR YOUR REAL ESTATE LEADS</div><h2>Every enquiry. Every conversation. <em>One lead journey.</em></h2><p>Replace scattered spreadsheets, inboxes and manual lead lists with a connected CRM workflow built around property enquiries and follow-ups.</p></div><div class="rex-features">
<article class="rex-card"><span class="rex-ico">◉</span><h3>Lead Tracking</h3><p>Organize property enquiries as contacts and opportunities, and track them through your configured real estate pipeline.</p></article>
<article class="rex-card"><span class="rex-ico">⚡</span><h3>CRM Automation</h3><p>Use workflows for lead assignment, follow-up tasks, reminders, stage updates and team notifications.</p></article>
<article class="rex-card"><span class="rex-ico">💬</span><h3>WhatsApp CRM</h3><p>Manage supported WhatsApp conversations, approved templates and interactive Flows alongside your customer CRM context.</p></article>
<article class="rex-card"><span class="rex-ico">✦</span><h3>AI Assistance</h3><p>Use AI summaries, reply drafts and contextual next-action suggestions to help your team follow up efficiently.</p></article>
</div></div></section>

<section class="rex-re-sources"><div class="container"><div class="rex-re-head"><div class="rex-re-eye">MULTI-SOURCE REAL ESTATE LEADS</div><h2>Bring leads from the channels <em>your buyers already use.</em></h2><p>Centralize supported lead sources so your agents can work from one CRM instead of checking multiple systems throughout the day.</p></div><div class="rex-sources">
<article class="rex-source"><div class="rex-source-top"><span class="rex-source-icon">f</span><span class="rex-source-tag">META</span></div><h3>Facebook & Instagram Leads</h3><p>Bring Meta Lead Ads enquiries into VistaarFlow and continue with assignment, workflows and CRM follow-up.</p></article>
<article class="rex-source"><div class="rex-source-top"><span class="rex-source-icon">WA</span><span class="rex-source-tag">CHAT</span></div><h3>WhatsApp Leads</h3><p>Keep supported WhatsApp customer conversations connected with contacts, opportunities, tasks and previous activity.</p></article>
<article class="rex-source"><div class="rex-source-top"><span class="rex-source-icon">99</span><span class="rex-source-tag">PORTAL</span></div><h3>99acres</h3><p>Bring supported property-portal enquiries into your real estate lead-management process.</p></article>
<article class="rex-source"><div class="rex-source-top"><span class="rex-source-icon">MB</span><span class="rex-source-tag">PORTAL</span></div><h3>MagicBricks</h3><p>Centralize supported MagicBricks enquiries so agents can manage them alongside the rest of their CRM leads.</p></article>
<article class="rex-source"><div class="rex-source-top"><span class="rex-source-icon">H</span><span class="rex-source-tag">PORTAL</span></div><h3>Housing.com</h3><p>Keep supported Housing.com enquiries connected to your contact and opportunity workflow.</p></article>
<article class="rex-source"><div class="rex-source-top"><span class="rex-source-icon">WEB</span><span class="rex-source-tag">FORM</span></div><h3>Website Leads</h3><p>Capture submitted website-form information and map relevant values to CRM fields for follow-up.</p></article>
<article class="rex-source"><div class="rex-source-top"><span class="rex-source-icon">✉</span><span class="rex-source-tag">EMAIL</span></div><h3>Email</h3><p>Keep supported customer email communication alongside the lead and opportunity context in your CRM.</p></article>
<article class="rex-source"><div class="rex-source-top"><span class="rex-source-icon">Z</span><span class="rex-source-tag">CONNECT</span></div><h3>Zapier</h3><p>Use supported Zapier connections to move information between VistaarFlow and compatible external apps.</p></article>
</div></div></section>

<section class="rex-re-wa"><div class="container rex-two"><div class="rex-re-copy"><div class="rex-re-eye">WHATSAPP AUTOMATION & TEMPLATES</div><h2>Follow up with property leads <em>without losing the conversation.</em></h2><p>Use approved WhatsApp templates and configured CRM workflows to keep lead follow-up consistent while customer context stays inside VistaarFlow.</p><div class="rex-checks"><div class="rex-check"><i>✓</i><div><strong>Approved WhatsApp templates</strong><p>Use approved templates for supported business messaging scenarios.</p></div></div><div class="rex-check"><i>✓</i><div><strong>Workflow-driven follow-up</strong><p>Connect lead events with configured tasks, reminders, assignment and supported messaging actions.</p></div></div><div class="rex-check"><i>✓</i><div><strong>WhatsApp Flow Builder</strong><p>Build supported interactive WhatsApp Flows and connect conversations with Contacts and Opportunities.</p></div></div></div></div>
<div class="rex-phone"><div class="rex-phone-in"><div class="rex-phone-head">WhatsApp • Property Enquiry</div><div class="rex-chat"><div class="rex-bubble rex-in">Hi, I'm interested in the 2 BHK. Can you share more details?</div><div class="rex-bubble rex-out">Thank you for your interest. Our team will assist you with the available property details.</div><div class="rex-template"><small>APPROVED TEMPLATE</small><b>Property Follow-up</b><p>Hi {{1}}, thank you for your interest. Would you like to schedule a call or site visit to discuss the property?</p></div><div class="rex-bubble rex-out">Template selected • Ready for review</div></div></div></div></div></section>

<section class="rex-re-track"><div class="container"><div class="rex-re-head"><div class="rex-re-eye">REAL ESTATE LEAD TRACKING</div><h2>Know exactly where <em>every property lead stands.</em></h2><p>Build a pipeline that matches your real estate process and move opportunities through the stages that matter to your team.</p></div><div class="rex-pipeline"><div class="rex-stage"><div class="rex-stage-title">NEW ENQUIRY</div><div class="rex-deal"><b>Rahul Sharma</b><small>2 BHK • Meta</small><span>New lead</span></div><div class="rex-deal"><b>Sana Khan</b><small>3 BHK • Website</small><span>New lead</span></div></div><div class="rex-stage"><div class="rex-stage-title">CONTACTED</div><div class="rex-deal"><b>Vikram Mehta</b><small>2 BHK • 99acres</small><span>Follow-up due</span></div></div><div class="rex-stage"><div class="rex-stage-title">SITE VISIT</div><div class="rex-deal"><b>Ananya Patel</b><small>3 BHK • WhatsApp</small><span>Visit scheduled</span></div></div><div class="rex-stage"><div class="rex-stage-title">NEGOTIATION</div><div class="rex-deal"><b>Arjun Rao</b><small>2 BHK • Housing.com</small><span>Opportunity active</span></div></div></div></div></section>

<section class="rex-re-ai"><div class="container rex-two"><div class="rex-ai-box"><div class="rex-ai-label">✦ VISTAARFLOW AI</div><div class="rex-ai-result"><b>AI Conversation Summary</b><p>Buyer is interested in a 2 BHK, requested pricing and payment-plan details, and is available for a call tomorrow evening.</p></div><div class="rex-suggest"><i>01</i><div><b>Share relevant property details</b><small>Buyer requested pricing and payment information.</small></div></div><div class="rex-suggest"><i>02</i><div><b>Create follow-up task</b><small>Call requested for tomorrow evening.</small></div></div><div class="rex-suggest"><i>03</i><div><b>Prepare AI reply</b><small>Generate a draft response using available conversation context.</small></div></div></div><div class="rex-re-copy"><div class="rex-re-eye">AI-POWERED REAL ESTATE CRM</div><h2>Understand buyer conversations. <em>Prepare the next action faster.</em></h2><p>Use AI assistance inside your CRM workflow to summarize conversations, prepare reply drafts and surface useful next-action suggestions.</p><div class="rex-checks"><div class="rex-check"><i>✦</i><div><strong>AI Summary</strong><p>Condense lengthy customer conversations into clear, useful context.</p></div></div><div class="rex-check"><i>✦</i><div><strong>AI Reply</strong><p>Prepare a contextual reply draft for your agent to review before sending.</p></div></div><div class="rex-check"><i>✦</i><div><strong>AI Suggestions</strong><p>Surface practical next steps from the available conversation and CRM context.</p></div></div></div></div></div></section>

<section class="rex-re-flow-sec"><div class="container"><div class="rex-re-head"><div class="rex-re-eye">CONNECTED REAL ESTATE WORKFLOW</div><h2>From new enquiry to <em>opportunity follow-up.</em></h2><p>Connect lead capture, assignment, communication, automation and AI in one real estate CRM journey.</p></div><div class="rex-flow"><div class="rex-step"><span class="rex-num">01</span><strong>Lead Captured</strong><small>Meta, WhatsApp, portal, web or email</small></div><div class="rex-step"><span class="rex-num">02</span><strong>CRM Record</strong><small>Contact data is organized</small></div><div class="rex-step"><span class="rex-num">03</span><strong>Agent Assigned</strong><small>Routed to the relevant user</small></div><div class="rex-step"><span class="rex-num">04</span><strong>WhatsApp / Email</strong><small>Customer communication continues</small></div><div class="rex-step"><span class="rex-num">05</span><strong>Automation</strong><small>Tasks, reminders and workflows</small></div><div class="rex-step"><span class="rex-num">06</span><strong>AI Assistance</strong><small>Summary, reply and suggestions</small></div><div class="rex-step"><span class="rex-num">07</span><strong>Opportunity</strong><small>Tracked through your pipeline</small></div></div></div></section>

<section class="rex-re-cta"><div class="container"><div class="rex-cta"><div><h2>One CRM for your complete real estate lead journey.</h2><p>Capture leads from multiple channels, automate follow-ups, manage WhatsApp communication and keep your agents focused on the right opportunities.</p></div><a class="rex-re-btn" href="https://app.vistaarflow.in/signup">Start 14 days free →</a></div></div></section>
</main>

<?php get_footer(); ?>