<?php
if (!defined('ABSPATH')) exit;

function vistaarflow_privacy_sections() {
  return [
    ['1. Information We Collect', ['Account information such as name, business name, email address, mobile number, billing details, user role, and login activity.','CRM data uploaded or created by customers, including contacts, leads, opportunities, tasks, notes, emails, WhatsApp messages, campaign records, forms, files, and media.','Integration data required to connect services such as WhatsApp Cloud API, Meta Lead Ads, Gmail, email providers, payment gateways, website widgets, and similar business tools.','Technical information such as IP address, device/browser details, cookies, session data, logs, usage events, error reports, and security audit records.']],
    ['2. How We Use Information', ['To provide, operate, secure, and improve Vistaar Flow CRM and related services.','To create and manage leads, contacts, opportunities, campaigns, tasks, automations, reports, billing, and customer support requests.','To send service notifications, security alerts, product updates, invoices, payment confirmations, and important account messages.','To detect abuse, prevent fraud, troubleshoot issues, maintain logs, and comply with applicable legal and regulatory requirements.']],
    ['3. Legal Basis And Indian Compliance', ['We process personal data in accordance with applicable Indian laws, including the Information Technology Act, 2000, the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, and the Digital Personal Data Protection Act, 2023, as and when applicable.','Where consent is required, customers are responsible for obtaining valid consent from their leads, contacts, users, and end customers before uploading or processing such data in the CRM.','Customers must ensure that WhatsApp, email, Meta, website form, and campaign communications comply with applicable consent, anti-spam, platform, and telecom rules.']],
    ['4. Data Sharing', ['We do not sell customer data.','We may share data with trusted service providers only when required to operate the CRM, such as hosting, storage, email delivery, WhatsApp/Meta APIs, payment processing, analytics, security, and customer support tools.','We may disclose information if required by law, court order, government authority, or to protect the rights, safety, and security of Techoceanhub Private Limited, Vistaar Flow, customers, or the public.']],
    ['5. Data Storage, Security, And Retention', ['We use reasonable security practices, access controls, encryption where appropriate, audit logs, and operational safeguards to protect customer data.','Customer data is retained for as long as the account is active, as needed to provide services, or as required for legal, tax, audit, dispute, and security purposes.','Customers may request deletion or export of their data, subject to applicable law, account ownership verification, outstanding obligations, backups, and legitimate retention requirements.']],
    ['6. Cookies And Tracking', ['We may use cookies and similar technologies for login sessions, security, preferences, analytics, performance, and product improvement.','Customers using the Vistaar Flow website widget on their own websites are responsible for disclosing such tracking and obtaining required visitor consent on their website.']],
    ['7. Customer Responsibilities', ['Customers are responsible for the accuracy, legality, consent, and permitted use of all contact, lead, campaign, and communication data uploaded into the CRM.','Customers must not use Vistaar Flow to send unlawful, misleading, abusive, unsolicited, or non-compliant communications.','Customers should configure user access carefully and remove access for users who no longer require it.']],
    ['8. Your Rights And Requests', ['Depending on applicable law, individuals may request access, correction, deletion, withdrawal of consent, or grievance redressal regarding personal data.','Because Vistaar Flow is primarily a business CRM, many requests relating to lead/contact data may need to be handled by the customer business that collected that data.']],
  ];
}

function vistaarflow_terms_sections() {
  return [
    ['1. Acceptance Of Terms', ['By accessing or using Vistaar Flow, you agree to these Terms & Conditions and any policies referenced here, including our Privacy Policy.','If you use Vistaar Flow on behalf of a business, you confirm that you are authorised to accept these Terms for that business.','If you do not agree with these Terms, you should not use the application or services.']],
    ['2. Product And Company', ['Vistaar Flow is a CRM and growth platform owned and operated by Techoceanhub Private Limited.','References to “Company”, “we”, “us”, or “our” mean Techoceanhub Private Limited.','References to “App”, “Platform”, “Product”, or “Vistaar Flow” mean the CRM software, website, APIs, integrations, widgets, and related services provided by us.']],
    ['3. Account Registration And Access', ['You must provide accurate account, business, billing, and contact information.','You are responsible for keeping login credentials secure and for all activity under your account.','Owners and admins are responsible for creating users, assigning roles, controlling access, and removing users who no longer need access.']],
    ['4. Permitted Use', ['You may use Vistaar Flow for lawful business CRM activities, including lead capture, contact management, pipeline management, communication, campaigns, automation, reporting, and billing.','You must not use Vistaar Flow for unlawful, fraudulent, abusive, harmful, misleading, spam, harassment, or unauthorised communication activities.','You must not attempt to disrupt, reverse engineer, overload, bypass security controls, or gain unauthorised access to the platform or another customer’s data.']],
    ['5. Customer Data And Consent', ['You remain responsible for the data you upload, import, collect, or process through Vistaar Flow, including leads, contacts, messages, files, and campaign data.','You must obtain required consent and permissions from your customers, leads, users, and website visitors before collecting or contacting them through WhatsApp, email, phone, Meta Lead Ads, forms, or other channels.','You must ensure your communications follow applicable Indian laws, platform policies, telecom rules, anti-spam expectations, and any other rules applicable to your business.']],
    ['6. Integrations And Third-Party Services', ['Vistaar Flow may connect with third-party services such as Meta, WhatsApp Cloud API, Gmail, email providers, payment gateways, hosting, storage, AI providers, and website tools.','Your use of third-party services is also governed by their own terms, pricing, permissions, limits, and policies.','We are not responsible for failures, suspensions, policy changes, pricing changes, downtime, rejected templates, API limits, or account restrictions caused by third-party platforms.']],
    ['7. Payments, Credits, Plans, And Billing', ['Subscription plans, included credits, add-ons, storage limits, user limits, and feature availability may vary by plan.','Credits may be consumed for billable platform actions such as WhatsApp messages, campaigns, flows, AI actions, or other usage-based events shown in the product or pricing page.','Fees are payable in advance unless otherwise agreed. Taxes, gateway charges, refunds, renewals, cancellations, and invoices will follow the plan and billing rules applicable at the time of purchase.']],
    ['8. AI Features', ['AI features are provided to assist with summaries, replies, recommendations, mapping suggestions, campaign copy, lead scoring, and similar productivity use cases.','AI output may be incomplete, inaccurate, or unsuitable for a particular situation. You must review and approve AI-generated content before using it with customers.','You are responsible for ensuring AI usage complies with your business policies, consent obligations, and applicable laws.']],
    ['9. Service Availability And Changes', ['We aim to provide a reliable service, but we do not guarantee uninterrupted, error-free, or always-available access.','We may update, improve, suspend, limit, or discontinue features for maintenance, security, legal compliance, platform changes, or business reasons.','We may modify these Terms from time to time. Continued use after updates means you accept the revised Terms.']],
    ['10. Suspension And Termination', ['We may suspend or terminate access if we believe there is misuse, non-payment, legal risk, security risk, policy violation, or breach of these Terms.','You may stop using the service or request account closure, subject to billing obligations, data retention requirements, backup cycles, and applicable law.']],
    ['11. Limitation Of Liability', ['To the maximum extent permitted by law, Techoceanhub Private Limited will not be liable for indirect, incidental, special, consequential, punitive, or loss-of-profit damages.','Our aggregate liability for claims relating to Vistaar Flow will be limited to the amount paid by you for the service during the three months before the event giving rise to the claim, unless applicable law requires otherwise.']],
    ['12. Governing Law And Disputes', ['These Terms are governed by the laws of India.','Subject to applicable law, courts in India having appropriate jurisdiction over Techoceanhub Private Limited will have jurisdiction for disputes relating to these Terms or Vistaar Flow.','Before filing a formal dispute, both parties should try to resolve the issue in good faith through written communication.']],
  ];
}
